### ISSUE TITLE
DeepSelect.sketchplugin file Missing from Zip

### ISSUE THREAD

**Issue by afrangi** [fhuel/DeepSelect#1]

**Comment by Christian3D** [comment]
Same issue, the plugin file is missing.

**Comment by fhuel** [comment]
Maybe you downloaded the source code and not the plugin itself?
Have you tried the release : https://github.com/fhuel/DeepSelect/releases/download/v0.0.2-1/plugin.sketchplugin.zip

**Comment by afrangi** [comment]
Hey, No I didn't check the release, I just assumed it will be part of the download zip file on the 'code tab'. I also didn't have much luck finding it in Runner! 

Thank you for sharing the release page and creating the plugin!

All the best

**Comment by fhuel** [comment]
Yes, it was actually not so clear. Thank you for letting me know!
